### ISSUE TITLE
libEvtGenExternal.so: undefined reference to `Pythia8::Pythia::readString(

### ISSUE THREAD

**Issue by wxie2013** [alisw/EVTGEN#1]
I'm using PYTHIA8.310 and EvtGen2.2.0 together to compile a code. The following error was produced: 

libEvtGenExternal.so: undefined reference to `Pythia8::Pythia::readString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)'

libEvtGenExternal.so: undefined reference to `Pythia8::Rndm::rndmEnginePtr(Pythia8::RndmEngine*)'

Could there be a version mismatch or I need to add some path to the makefile. 

Thanks

**Comment by wxie2013** [comment]
I used the following conda command to install ROOT, pythia98 and evtgen:

conda install -c conda-forge root -y
conda install -c conda-forge pythia8 -y
conda install -c conda-forge evtgen -y

**Comment by wxie2013** [comment]
Yes, indeed. This is a version mismatch.  PYTHIA8.304 works fine with EvtGen2.2.0.  Would be nice to update accordingly.

**Comment by chrisburr** [comment]
I stumbled upon this while debugging a similar issue. It should be fixed by https://github.com/conda-forge/evtgen-feedstock/pull/5

**Comment by wxie2013** [comment]
What's the command to install the feedstock#5?  I tried the following but it can't find the packages: 

conda install -c conda-forge evtgen-feedstock#5
